### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by EricHeredia** [EricHeredia/local-eats#2]
- [ ] Add point system. Marking as been there grants been there points. Higher 
  points grant higher tiers (iron, bronze, silver, gold, plat, diamond, etc.)

- [ ] Change formatting of localStorage to work with points system and to easier
  manipulate data.

- [ ] Make each item clickable to show more information. Address and phone for 
  quick call / directions.

- [ ] Do more research and implement react hooks. Focus on clean functional 
  components. Keep everything scalable.

- [ ] Keep style simple, but interesting. Responsive but leaning more towards 
  mobile.

------------------------------------------------------------

- [ ] Set up mongoDB and express

- [ ] Create user sign-up/login

------------------------------------------------------------

- [ ] Research and switch to Apollo GraphQL
